### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by drochecsp2017** [gibboa/Open_IO#21]
[error_report2.txt](https://github.com/gibboa/Open_IO/files/3082871/error_report2.txt)
While I haven't seen much of the heap error recently ever since I fixed the infinite loop (see Mattermost), this one has started to crop up a fair deal. Seems like "`p1.path[p1.length*6]`" is sometimes undefined, causing a fatal exception. Truth be told, I'm not even certain what `p1.path` *is*, so I suppose this will be a test of our documentation too.

_Note:_ I believe that I've added a few lines of code to `server.js` while bugfixing, so the line in the error may not entirely match the line in your own file. It should read `p1.pos_list.push([p1.path[p1.length*6][0], p1.path[p1.length*6][1]]);`, within function `checkGameEvents()`.

**Comment by drochecsp2017** [comment]
Update: played the game for a bit; managed to get up to 74 apples collected before hitting the TypeError. Curiously,

* My score was only listed as 690, not 740, meaning five apples had been dropped from the score counter somewhere

* No memory error, despite this being the exact sort of scenario that would generate one

* I never hit a wall; the error hit me over the course of normal gameplay

Combined, this information leads me to suspect that the TypeError has "replaced" the memory error, so to speak. Going to leave that issue open just in case, but this is definitely my main priority as of now.

**Comment by gibboa** [comment]
Hopefully fixed it, I think it occured (when away form the edge) when foods randomly spawn on top of the snake... now foods avoid snakes, and also snakes can eat multiple food at the same time... because path is much larger.... need more testing to verify though

**Comment by drochecsp2017** [comment]
After playtesting @gibboa 's latest push, can confirm the bug still exists. I played the game until I had collected ~200 apples, then suicided into a wall. Some bizarre behavior ensued: the snake's entire body turned to apples, not just every other segment, and it began expanding *backwards* at an extremely rapid pace for several seconds (at which point the now-familiar TypeError occurred).

I suspect what happened was that apples began to spawn on the snake's now-deceased head, which it would then eat despite being dead. Because it was effectively being fed food as fast as the game could spawn it, the snake proceeded to fill up it's entire array of stored past locations it uses to grow until it hit the end of the list, causing the TypeError. Will need further testing still to be sure, though; see Mattermost for any further details.

An image of the game board immediately after the glitch:

<img width="407" alt="mass_apples" src="https://user-images.githubusercontent.com/22242003/56262722-f060df80-60ad-11e9-997f-678c35ba4c75.PNG">


My command line immediately after the glitch:

<img width="552" alt="mass_apples_cmd" src="https://user-images.githubusercontent.com/22242003/56262745-0e2e4480-60ae-11e9-9fcd-34336f6735ae.PNG">

**Comment by gibboa** [comment]
Thanks, all of these issues should be fixed. The "Cannot read property '0' of undefined" relates to out of bounds access on the path array which should no longer be possible, as we are growing at what I believe to be the upper bound on its usage (which is not efficient, but is safest). Also the foods free foods are capped at 10 now so we wont have the food explosions when snakes die. (it can go over 10 with the converted food though) Also snake deaths are fixed so the snakes will not create a cycle of dying->producing food->eating food->dying producing food-> and so on. Also there is now increased separation of converted foods from dead snakes. I'm closing the issue as I have not been able to recreate the errors since the fixes... but if someone can recreate them, please open a new issue.
